<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonteCarlo.Core\MonteCarlo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../MonteCarlo.Excel/MonteCarlo.Excel/SimulationValidation.cs" Link="Simulation/SimulationValidation.cs" />
    <Compile Include="../MonteCarlo.Excel/MonteCarlo.Excel/SimulationWorkbook.cs" Link="Simulation/SimulationWorkbook.cs" />
    <Compile Include="../MonteCarlo.Excel/MonteCarlo.Excel/SimulationExecution.cs" Link="Simulation/SimulationExecution.cs" />
    <Compile Include="../MonteCarlo.Excel/MonteCarlo.Excel/SimulationRunResult.cs" Link="Results/SimulationRunResult.cs" />
    <Compile Include="../MonteCarlo.Excel/MonteCarlo.Excel/SimulationModel.cs" Link="Results/SimulationModel.cs" />
    <Compile Include="../MonteCarlo.Excel/MonteCarlo.Excel/SensitivityResult.cs" Link="Results/SensitivityResult.cs" />
  </ItemGroup>

</Project>
